spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-google-client-id
            client-secret: myTestGoogleClientSecret
          keycloak:
            client-id: test-keycloak-client-id
            client-secret: myTestKeycloakClientSecret
        provider:
          keycloak:
            base-uri: "http://localhost:8081/realms/vscp"

logging:
  level:
    org:
      springframework:
        security: DEBUG