### get config anonymous
GET http://localhost:8080/config/

### get config authenticated
GET http://localhost:8080/config/
Authorization: Basic user password

### update config anonymous
POST http://localhost:8080/config/
Content-Type: application/json

{
  "roundInMinutes": 12,
  "warningTimeInMinutes": 1,
  "blindLevels": [1,2,4,8]
}

### update config authenitcated
POST http://localhost:8080/config/
Authorization: Basic admin password
Content-Type: application/json

{
  "roundInMinutes": 12,
  "warningTimeInMinutes": 1,
  "blindLevels": [1,2,4,8]
}

### error testing
GET http://localhost:8080/config/error/
Authorization: Basic user password

############### OAUTH2
### get config authenticated
GET http://localhost:8080/config/
Authorization: Bearer {{$auth.token("google")}}

############### OAUTH2 Keycloak
### get config authenticated
GET http://localhost:8080/config/
Authorization: Bearer {{$auth.token("keycloak")}}
